name: Docker image
on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build & push docker image
    runs-on: self-hosted
    steps:
      - name: Docker Build
        run: docker build -t test .
    with:
      images: ${{ github.repository }}